### ISSUE TITLE
404 error on setting image tag src

### ISSUE THREAD

**Issue by JordanTheriault** [humphd/brackets#262] opened 2015-05-11 19:00 UTC
Whenever a string of any value is added to src of the img tag within the editor, a 404 error occurs. The 404 error occurs on every stroke after src is specified.

This error does not take place in the CSS url() case.

This happens despite a blob url being generated in the case of the selfie extension. Further, the image rendering in the preview works.

This leads to a large number of requests being made to the server and has a high cost.

![example](https://cloud.githubusercontent.com/assets/5931078/7572638/c0249262-f7ed-11e4-9021-17fd3cde95f3.gif)

**Comment by JordanTheriault** [comment] 2015-05-11 19:30
Image will display is the string to a valid file is removed and re-added, so it is likely not an issue with nohost.

This seems to only when a diff check takes place.

**Comment by sedge** [comment] 2015-05-11 19:33
This appears to happen on any change to the editor after the `src` attribute of an `<img>` tag has been populated.

**Comment by humphd** [comment] 2015-05-11 20:11
This turns out to be caused by [https://github.com/KeniMorri/HTMLHinter](HTMLHinter), which is where we use SlowParse.  @Pomax, any ideas what would cause SlowParse to actually try and load an `img`'s `src` URL?

Let's disable HTMLHinter on Bramble until we fix this.

**Comment by humphd** [comment] 2015-05-11 20:16
@gideonthomas confirms this is being caused by slowparse.

**Comment by Pomax** [comment] 2015-05-11 20:40
Slowparse builds an active DOM, so the quickest path to success here will be to write a dropin for the `document` API we're using in https://github.com/mozilla/slowparse/blob/gh-pages/src/DOMBuilder.js, with minimal `Node` (the data structure, not Node.js) implementations for appending children and setting attributes.

**Comment by humphd** [comment] 2015-05-12 16:56
This is being fixed in https://github.com/mozilla/slowparse/pull/79

**Comment by gideonthomas** [comment] 2015-05-18 18:38
will be fixed with https://github.com/humphd/brackets/issues/263

**Comment by Pomax** [comment] 2015-05-18 23:19
Slowparse has been patched and updated.

**Comment by gideonthomas** [comment] 2015-05-20 19:48
Fixed in 40bd5f4040034628cc75b7b10577ce9016d5cc39

**Closed by gideonthomas** 2015-05-20 19:48 UTC
Labels: bug
